language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO='Django==1.4.*'
  - DJANGO='Django==1.5.*'
  - DJANGO='Django==1.6.*'
  - DJANGO='Django==1.7.*'
  - DJANGO='Django==1.8.*'
  - DJANGO='Django==1.9.*'
matrix:
  exclude:
    # Django >= 1.7 does not support Python 2.6
    - python: "2.6"
      env: DJANGO='Django==1.7.*'
    - python: "2.6"
      env: DJANGO='Django==1.8.*'
    - python: "2.6"
      env: DJANGO='Django==1.9.*'
install:
  - pip install $DJANGO
script:
  - make test
